
package com.example.spring.soap.client.loanandeligibility;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoanAndEligibilityPortType", targetNamespace = "http://www.example.com/spring/soap/api/loanEligibility")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanAndEligibilityPortType {


    /**
     * 
     * @param customerRequest
     */
    @WebMethod(operationName = "Customer")
    @Oneway
    public void customer(
        @WebParam(name = "CustomerRequest", targetNamespace = "http://www.example.com/spring/soap/api/loanEligibility", partName = "CustomerRequest")
        CustomerRequest customerRequest);

}
